---
- name: Build EE for Azure
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars_files:
    - vars/ah_ee_new.yml
    - vars/auth.yml
    - vars/settings.yml
    - vars/vars.yml
    - vars/vault.yml
  tasks:
    - name: Include ee_builder role
      ansible.builtin.include_role:
        name: infra.ee_utilities.ee_builder
        
